### ISSUE TITLE
Support the latest edition of WordPress, please. 

### ISSUE THREAD

**Issue by ajmz** [ryansborn/WP_HTML5_Outliner#2]
Can not find the plugin of workflowy or dynalist for WordPress.
😒
What about outline structure in WordPress article?

**Comment by ryansborn** [comment]
This plugin is not like workflowy or dynalist. It generates an outline from a webpage. For comparison, see the [W3C Markup Validation Service](https://validator.w3.org/#validate_by_uri+with_options).

Also, unofficially, this plugin works in WordPress 5.2.1, the latest version as of this posting. Officially, it works in versions 3.3 to 5.1.1, as indicated on [the plugin's WP repo page](https://wordpress.org/plugins/wp-html5-outliner/)
